name: Cloud Functions

on:
  push:
  workflow_dispatch:

concurrency: ${{ github.ref }}-${{ github.workflow }}

env:
  ENV_FILE: env.yaml

  REGION: us-central1
  GCP_SA: bivuanem@voltaic-country-280607.iam.gserviceaccount.com
  FN: vuanem-marketing-mysql-${{ github.ref_name }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: ${{ env.ENV_KEY }}

      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - uses: google-github-actions/setup-gcloud@v0

      - uses: snok/install-poetry@v1

      - run: poetry export --without-hashes -o requirements.txt

      - run: |
          echo "GH_REF: ${{ github.ref_name }}" >> ${{ env.ENV_FILE }}

      - run: >-
          gcloud functions deploy ${{ env.FN }}
          --entry-point=main
          --region=us-central1
          --timeout=530
          --memory=8192MB
          --runtime=python39
          --trigger-http
          --no-user-output-enabled
          --service-account=${{ env.GCP_SA }}
          --env-vars-file=${{ env.ENV_FILE }}
