name: deploy
on:
  push:
    branches: [master]
  workflow_dispatch:

env:
  NAME: vuanem_mysql
  PROJECT_ID: ${{ secrets.PROJECT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Deploy to Cloud Functions
      run: >-
        gcloud functions deploy ${{ env.NAME }}
        --timeout=180
        --memory=1024MB
        --entry-point=main
        --runtime=python38
        --trigger-http
        --project=${{ secrets.PROJECT_ID }}
        --service-account=${{ secrets.GCP_SA }}
        --set-env-vars=MYSQL_UID=${{ secrets.MYSQL_UID }},MYSQL_PWD=${{ secrets.MYSQL_PWD }},MYSQL_SERVER=${{ secrets.MYSQL_SERVER }},TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }},TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}
